name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        # build release artifacts source and Javadoc jars + publish the artifacts
    - name: Build release artifacts
      run: ./gradlew
            -Poss.username=${{ secrets.OSSRH_USERNAME }}
            -Poss.password=${{ secrets.OSSRH_PASSWORD }}
            :library:assembleRelease

    # Generates source and Javadoc jar artifacts
    - name: Create source and Javadoc jar
      run: ./gradlew
            -Poss.username=${{ secrets.OSSRH_USERNAME }}
            -Poss.password=${{ secrets.OSSRH_PASSWORD }}
            :library:assembleRelease
            :library:withJavadocJar :library:withSourceJar

    # Runs upload, and then closes & releases the repository
    - name: Publish to MavenCentral
      run: ./gradlew
            -Poss.username=${{ secrets.OSSRH_USERNAME }}
            -Poss.password=${{ secrets.OSSRH_PASSWORD }}
            -PsigningInMemoryKeyId=${{ secrets.SIGNINGINMEMORYKEYID }}
            -PsigningInMemoryKeyPassword=${{ secrets.SIGNINGINMEMORYKEYPASSWORD }}
            -PsigningInMemoryKey=${{ secrets.SIGNINGINMEMORYKEY }}
            publish --max-workers 1
      env:
        ossUsername: ${{ secrets.OSSRH_USERNAME }}
        ossPassword: ${{ secrets.OSSRH_PASSWORD }}
        signingInMemoryKeyId: ${{ secrets.SIGNINGINMEMORYKEYID }}
        signingInMemoryKeyPassword: ${{ secrets.SIGNINGINMEMORYKEYPASSWORD }}
        signingInMemoryKey: ${{ secrets.SIGNINGINMEMORYKEY }}
