name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        # build release artifacts source and Javadoc jars + publish the artifacts
    - name: Build release artifacts
      run: ./gradlew :library:assembleRelease
      env:
        oss.username:${{ secrets.OSSRH_USERNAME }}
        oss.password:${{ secrets.OSSRH_PASSWORD }}
        signing.keyId:${{ secrets.SIGNING_KEY_ID }}
        signing.password:${{ secrets.SIGNING_PASSWORD }}
        signingsecretKeyRingFile:${{ secrets.SIGNING_KEY }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

    # Generates source and Javadoc jar artifacts
    - name: Create source and Javadoc jar
      run: ./gradlew :library:withJavadocJar :library:withSourceJar
      env:
        oss.username:${{ secrets.OSSRH_USERNAME }}
        oss.password:${{ secrets.OSSRH_PASSWORD }}
        signing.keyId:${{ secrets.SIGNING_KEY_ID }}
        signing.password:${{ secrets.SIGNING_PASSWORD }}
        signingsecretKeyRingFile:${{ secrets.SIGNING_KEY }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

    # Runs upload, and then closes & releases the repository
    - name: Publish to MavenCentral
      run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
      env:
        oss.username:${{ secrets.OSSRH_USERNAME }}
        oss.password:${{ secrets.OSSRH_PASSWORD }}
        signing.keyId:${{ secrets.SIGNING_KEY_ID }}
        signing.password:${{ secrets.SIGNING_PASSWORD }}
        signingsecretKeyRingFile:${{ secrets.SIGNING_KEY }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}