name: Android CI/CD

on:
  push:
    branches: [ master, feature/cd-for-google-play ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      # Create a build number based on timestamp / UTC time
      - name: set release date
        run: |
          echo "BUILD_NUMBER=$(date +"%s")" >> ${GITHUB_ENV}

      # Decode the keystore file containing the signing key
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './demo/secrets'
          fileName: '1gravity.keystore'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      # Decode the Google Play api key file
      - name: Decode Google Play API key
        id: decode_api_key
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './demo/secrets'
          fileName: 'google-play-api-key.json'
          encodedString: ${{ secrets.GOOGLE_PLAY_API_KEY }}

      # build release artifacts
      - name: Build release artifacts
        run: ./gradlew
          -PBUILD_NUMBER="${{ env.BUILD_NUMBER }}"
          -PgooglePlayApiKey=${{ steps.decode_api_key.outputs.filePath }}
          -PONEGRAVITY_KEYSTORE_FILE=${{ steps.decode_keystore.outputs.filePath }}
          -PONEGRAVITY_KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          -PONEGRAVITY_OPENSOURCE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          -PONEGRAVITY_OPENSOURCE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          :demo:bundleRelease --stacktrace

      # Publish to Google Play
      - name: Publish to Google Play
        run: ./gradlew
          -PBUILD_NUMBER="${{ env.BUILD_NUMBER }}"
          -PgooglePlayApiKey=${{ steps.decode_api_key.outputs.filePath }}
          -PONEGRAVITY_KEYSTORE_FILE=${{ steps.decode_keystore.outputs.filePath }}
          -PONEGRAVITY_KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          -PONEGRAVITY_OPENSOURCE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          -PONEGRAVITY_OPENSOURCE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          :demo:publishBundle --max-workers 1
